# Project: 03-运算符
# Makefile created by Dev-C++ 6.7.5

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = 算数运算符.o 赋值运算符.o 比较运算符.o 逻辑运算符.o
LINKOBJ  = 算数运算符.o 赋值运算符.o 比较运算符.o 逻辑运算符.o
LIBS     = -L"c:/software/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/" -L"c:/software/dev-cpp/mingw32/lib/gcc/" -L"c:/software/dev-cpp/mingw32/mingw32/lib/" -L"c:/software/dev-cpp/mingw32/lib/" -L"C:/software/Dev-Cpp/MinGW32/lib" -L"C:/software/Dev-Cpp/MinGW32/mingw32/lib" -g3 -static
INCS     = -I"c:/software/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/include" -I"c:/software/dev-cpp/mingw32/include" -I"c:/software/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/include-fixed"
CXXINCS  = -I"c:/software/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/include/c++" -I"c:/software/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/include/c++/mingw32" -I"c:/software/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/include/c++/backward" -I"c:/software/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/include" -I"c:/software/dev-cpp/mingw32/include" -I"c:/software/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/include-fixed"
BIN      = 03-运算符.exe
CXXFLAGS = $(CXXINCS) -Wall -Wextra -g3
ENCODINGS = -finput-charset=utf-8 -fexec-charset=gbk
CFLAGS   = $(INCS) -Wall -Wextra -g3
RM       = del /q /f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "$(BIN)" $(LIBS)

算数运算符.o: 算数运算符.cpp
	$(CPP) -c 算数运算符.cpp -o 算数运算符.o $(CXXFLAGS) 

赋值运算符.o: 赋值运算符.cpp
	$(CPP) -c 赋值运算符.cpp -o 赋值运算符.o $(CXXFLAGS) 

比较运算符.o: 比较运算符.cpp
	$(CPP) -c 比较运算符.cpp -o 比较运算符.o $(CXXFLAGS) 

逻辑运算符.o: 逻辑运算符.cpp
	$(CPP) -c 逻辑运算符.cpp -o 逻辑运算符.o $(CXXFLAGS) 
